name: Bedman
version: 1.1.0
depend: []
softdepend: []
loadbefore: []

main: org.yuxuan.bedman.PluginMain

commands:
  bedman:
    description: Open bedman teleportation menu
    aliases: bm
    permission: bedman.open
    usage: /bedman [player]
  bedinfo:
    description: Get player bed info
    aliases: bi
    permission: bedman.info
    usage: /bedinfo [player]
  tpbed:
    description: Teleport to player's bed location
    aliases: tpb
    permission: bedman.tp
    usage: /tpbed [player]
permissions:
  bedman.open:
    description: Allows open bedman teleportation menu.
    default: op
  bedman.info:
    description: Allows get player bed info.
    default: op
  bedman.tp:
    description: Allows teleport to player's bed location.
    default: op
